before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/flatend/
    id: "flatend"
    binary: flatend
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'